allowHosts:
  - "stethoscope://main"
hostLabels:
  - pattern: "^http://127.0.0.1:3000"
    name: Local Server
policyServer:
testHosts:
  # - url: "http://foo.bar.com"
  #   label: Display Value
deprecationNotice:
  heading: >
    The Stethocsope Desktop application is deprecated and no longer supported.
  subHeading:
  linkUrl:
  linkText:
